// Currency data for countries (exchange rates relative to USD)
// Rates are updated daily via currencyService
// This object serves as both default rates and gets updated with live rates
export const currencyData = {
  'Afghanistan': { currency: 'AFN', symbol: '؋', rate: 88.5 },
  'Antigua and Barbuda': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Antigua': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Albania': { currency: 'ALL', symbol: 'L', rate: 92.5 },
  'Algeria': { currency: 'DZD', symbol: 'د.ج', rate: 135.0 },
  'Andorra': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Angola': { currency: 'AOA', symbol: 'Kz', rate: 825.0 },
  'Argentina': { currency: 'ARS', symbol: '$', rate: 350.0 },
  'Armenia': { currency: 'AMD', symbol: '֏', rate: 385.0 },
  'Australia': { currency: 'AUD', symbol: 'A$', rate: 1.53 },
  'Austria': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Azerbaijan': { currency: 'AZN', symbol: '₼', rate: 1.70 },
  'Bahamas': { currency: 'BSD', symbol: 'B$', rate: 1.0 },
  'Bahrain': { currency: 'BHD', symbol: '.د.ب', rate: 0.38 },
  'Bangladesh': { currency: 'BDT', symbol: '৳', rate: 110.0 },
  'Barbados': { currency: 'BBD', symbol: 'Bds$', rate: 2.0 },
  'Belarus': { currency: 'BYN', symbol: 'Br', rate: 3.25 },
  'Belgium': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Belize': { currency: 'BZD', symbol: 'BZ$', rate: 2.0 },
  'Benin': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Bhutan': { currency: 'BTN', symbol: 'Nu.', rate: 83.2 },
  'Bolivia': { currency: 'BOB', symbol: 'Bs.', rate: 6.91 },
  'Bosnia and Herzegovina': { currency: 'BAM', symbol: 'KM', rate: 1.80 },
  'Botswana': { currency: 'BWP', symbol: 'P', rate: 13.5 },
  'Brazil': { currency: 'BRL', symbol: 'R$', rate: 4.95 },
  'Brunei': { currency: 'BND', symbol: 'B$', rate: 1.34 },
  'Bulgaria': { currency: 'BGN', symbol: 'лв', rate: 1.80 },
  'Burkina Faso': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Burundi': { currency: 'BIF', symbol: 'FBu', rate: 2850.0 },
  'Cambodia': { currency: 'KHR', symbol: '៛', rate: 4100.0 },
  'Cameroon': { currency: 'XAF', symbol: 'FCFA', rate: 605.0 },
  'Canada': { currency: 'CAD', symbol: 'C$', rate: 1.36 },
  'Cape Verde': { currency: 'CVE', symbol: '$', rate: 102.0 },
  'Central African Republic': { currency: 'XAF', symbol: 'FCFA', rate: 605.0 },
  'Chad': { currency: 'XAF', symbol: 'FCFA', rate: 605.0 },
  'Chile': { currency: 'CLP', symbol: '$', rate: 890.0 },
  'China': { currency: 'CNY', symbol: '¥', rate: 7.24 },
  'Colombia': { currency: 'COP', symbol: '$', rate: 3950.0 },
  'Comoros': { currency: 'KMF', symbol: 'CF', rate: 455.0 },
  'Congo': { currency: 'XAF', symbol: 'FCFA', rate: 605.0 },
  'Costa Rica': { currency: 'CRC', symbol: '₡', rate: 520.0 },
  'Croatia': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Cuba': { currency: 'CUP', symbol: '₱', rate: 24.0 },
  'Cyprus': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Czech Republic': { currency: 'CZK', symbol: 'Kč', rate: 22.5 },
  'Denmark': { currency: 'DKK', symbol: 'kr', rate: 6.85 },
  'Djibouti': { currency: 'DJF', symbol: 'Fdj', rate: 177.0 },
  'Dominica': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Dominican Republic': { currency: 'DOP', symbol: 'RD$', rate: 57.0 },
  'East Timor': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Ecuador': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Egypt': { currency: 'EGP', symbol: 'E£', rate: 30.9 },
  'El Salvador': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Equatorial Guinea': { currency: 'XAF', symbol: 'FCFA', rate: 605.0 },
  'Eritrea': { currency: 'ERN', symbol: 'Nfk', rate: 15.0 },
  'Estonia': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Ethiopia': { currency: 'ETB', symbol: 'Br', rate: 56.5 },
  'Fiji': { currency: 'FJD', symbol: 'FJ$', rate: 2.24 },
  'Finland': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'France': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Gabon': { currency: 'XAF', symbol: 'FCFA', rate: 605.0 },
  'Gambia': { currency: 'GMD', symbol: 'D', rate: 65.0 },
  'Georgia': { currency: 'GEL', symbol: '₾', rate: 2.65 },
  'Germany': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Ghana': { currency: 'GHS', symbol: 'GH₵', rate: 12.0 },
  'Greece': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Grenada': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Guatemala': { currency: 'GTQ', symbol: 'Q', rate: 7.85 },
  'Guinea': { currency: 'GNF', symbol: 'FG', rate: 8600.0 },
  'Guinea-Bissau': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Guyana': { currency: 'GYD', symbol: 'G$', rate: 209.0 },
  'Haiti': { currency: 'HTG', symbol: 'G', rate: 132.0 },
  'Honduras': { currency: 'HNL', symbol: 'L', rate: 24.7 },
  'Hungary': { currency: 'HUF', symbol: 'Ft', rate: 355.0 },
  'Iceland': { currency: 'ISK', symbol: 'kr', rate: 138.0 },
  'India': { currency: 'INR', symbol: '₹', rate: 83.2 },
  'Indonesia': { currency: 'IDR', symbol: 'Rp', rate: 15650.0 },
  'Iran': { currency: 'IRR', symbol: '﷼', rate: 42000.0 },
  'Iraq': { currency: 'IQD', symbol: 'ع.د', rate: 1310.0 },
  'Ireland': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Israel': { currency: 'ILS', symbol: '₪', rate: 3.65 },
  'Italy': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Ivory Coast': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Jamaica': { currency: 'JMD', symbol: 'J$', rate: 155.0 },
  'Japan': { currency: 'JPY', symbol: '¥', rate: 149.5 },
  'Jordan': { currency: 'JOD', symbol: 'JD', rate: 0.71 },
  'Kazakhstan': { currency: 'KZT', symbol: '₸', rate: 450.0 },
  'Kenya': { currency: 'KES', symbol: 'KSh', rate: 145.0 },
  'Kiribati': { currency: 'AUD', symbol: 'A$', rate: 1.53 },
  'Kosovo': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Kuwait': { currency: 'KWD', symbol: 'KD', rate: 0.31 },
  'Kyrgyzstan': { currency: 'KGS', symbol: 'с', rate: 87.5 },
  'Laos': { currency: 'LAK', symbol: '₭', rate: 20500.0 },
  'Latvia': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Lebanon': { currency: 'LBP', symbol: 'ل.ل', rate: 89500.0 },
  'Lesotho': { currency: 'LSL', symbol: 'L', rate: 18.5 },
  'Liberia': { currency: 'LRD', symbol: 'L$', rate: 185.0 },
  'Libya': { currency: 'LYD', symbol: 'ل.د', rate: 4.82 },
  'Liechtenstein': { currency: 'CHF', symbol: 'Fr', rate: 0.88 },
  'Lithuania': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Luxembourg': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Macedonia': { currency: 'MKD', symbol: 'ден', rate: 56.5 },
  'Madagascar': { currency: 'MGA', symbol: 'Ar', rate: 4550.0 },
  'Malawi': { currency: 'MWK', symbol: 'MK', rate: 1680.0 },
  'Malaysia': { currency: 'MYR', symbol: 'RM', rate: 4.72 },
  'Maldives': { currency: 'MVR', symbol: 'Rf', rate: 15.4 },
  'Mali': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Malta': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Marshall Islands': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Mauritania': { currency: 'MRU', symbol: 'UM', rate: 36.5 },
  'Mauritius': { currency: 'MUR', symbol: '₨', rate: 45.5 },
  'Mexico': { currency: 'MXN', symbol: '$', rate: 17.2 },
  'Micronesia': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Moldova': { currency: 'MDL', symbol: 'L', rate: 17.8 },
  'Monaco': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Mongolia': { currency: 'MNT', symbol: '₮', rate: 3450.0 },
  'Montenegro': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Morocco': { currency: 'MAD', symbol: 'د.م.', rate: 10.1 },
  'Mozambique': { currency: 'MZN', symbol: 'MT', rate: 63.5 },
  'Myanmar': { currency: 'MMK', symbol: 'K', rate: 2100.0 },
  'Namibia': { currency: 'NAD', symbol: 'N$', rate: 18.5 },
  'Nauru': { currency: 'AUD', symbol: 'A$', rate: 1.53 },
  'Nepal': { currency: 'NPR', symbol: '₨', rate: 133.0 },
  'Netherlands': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'New Zealand': { currency: 'NZD', symbol: 'NZ$', rate: 1.65 },
  'Nicaragua': { currency: 'NIO', symbol: 'C$', rate: 36.5 },
  'Niger': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Nigeria': { currency: 'NGN', symbol: '₦', rate: 1550.0 },
  'North Korea': { currency: 'KPW', symbol: '₩', rate: 900.0 },
  'Norway': { currency: 'NOK', symbol: 'kr', rate: 10.8 },
  'Oman': { currency: 'OMR', symbol: 'ر.ع.', rate: 0.38 },
  'Pakistan': { currency: 'PKR', symbol: '₨', rate: 278.0 },
  'Palau': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Palestine': { currency: 'ILS', symbol: '₪', rate: 3.65 },
  'Panama': { currency: 'PAB', symbol: 'B/.', rate: 1.0 },
  'Papua New Guinea': { currency: 'PGK', symbol: 'K', rate: 3.75 },
  'Paraguay': { currency: 'PYG', symbol: '₲', rate: 7250.0 },
  'Peru': { currency: 'PEN', symbol: 'S/', rate: 3.75 },
  'Philippines': { currency: 'PHP', symbol: '₱', rate: 56.5 },
  'Poland': { currency: 'PLN', symbol: 'zł', rate: 4.05 },
  'Portugal': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Qatar': { currency: 'QAR', symbol: 'ر.ق', rate: 3.64 },
  'Romania': { currency: 'RON', symbol: 'lei', rate: 4.56 },
  'Russia': { currency: 'RUB', symbol: '₽', rate: 92.0 },
  'Rwanda': { currency: 'RWF', symbol: 'FRw', rate: 1285.0 },
  'Saint Kitts and Nevis': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Saint Lucia': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Saint Vincent and the Grenadines': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Samoa': { currency: 'WST', symbol: 'T', rate: 2.72 },
  'San Marino': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Sao Tome and Principe': { currency: 'STN', symbol: 'Db', rate: 22.7 },
  'Saudi Arabia': { currency: 'SAR', symbol: 'ر.س', rate: 3.75 },
  'Senegal': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Serbia': { currency: 'RSD', symbol: 'дин', rate: 108.0 },
  'Seychelles': { currency: 'SCR', symbol: '₨', rate: 13.2 },
  'Sierra Leone': { currency: 'SLL', symbol: 'Le', rate: 22500.0 },
  'Singapore': { currency: 'SGD', symbol: 'S$', rate: 1.34 },
  'Slovakia': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Slovenia': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Solomon Islands': { currency: 'SBD', symbol: 'SI$', rate: 8.45 },
  'Somalia': { currency: 'SOS', symbol: 'Sh', rate: 570.0 },
  'South Africa': { currency: 'ZAR', symbol: 'R', rate: 18.5 },
  'South Korea': { currency: 'KRW', symbol: '₩', rate: 1320.0 },
  'South Sudan': { currency: 'SSP', symbol: '£', rate: 1305.0 },
  'Spain': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Sri Lanka': { currency: 'LKR', symbol: '₨', rate: 325.0 },
  'Sudan': { currency: 'SDG', symbol: 'ج.س.', rate: 600.0 },
  'Suriname': { currency: 'SRD', symbol: '$', rate: 36.0 },
  'Swaziland': { currency: 'SZL', symbol: 'L', rate: 18.5 },
  'Sweden': { currency: 'SEK', symbol: 'kr', rate: 10.6 },
  'Switzerland': { currency: 'CHF', symbol: 'Fr', rate: 0.88 },
  'Syria': { currency: 'SYP', symbol: '£S', rate: 13000.0 },
  'Taiwan': { currency: 'TWD', symbol: 'NT$', rate: 31.5 },
  'Tajikistan': { currency: 'TJS', symbol: 'ЅМ', rate: 10.9 },
  'Tanzania': { currency: 'TZS', symbol: 'TSh', rate: 2510.0 },
  'Thailand': { currency: 'THB', symbol: '฿', rate: 35.8 },
  'Togo': { currency: 'XOF', symbol: 'CFA', rate: 605.0 },
  'Tonga': { currency: 'TOP', symbol: 'T$', rate: 2.35 },
  'Trinidad and Tobago': { currency: 'TTD', symbol: 'TT$', rate: 6.78 },
  'Tunisia': { currency: 'TND', symbol: 'د.ت', rate: 3.12 },
  'Turkey': { currency: 'TRY', symbol: '₺', rate: 32.5 },
  'Turkmenistan': { currency: 'TMT', symbol: 'm', rate: 3.50 },
  'Tuvalu': { currency: 'AUD', symbol: 'A$', rate: 1.53 },
  'Uganda': { currency: 'UGX', symbol: 'USh', rate: 3750.0 },
  'Ukraine': { currency: 'UAH', symbol: '₴', rate: 36.5 },
  'United Arab Emirates': { currency: 'AED', symbol: 'د.إ', rate: 3.67 },
  'England': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'Scotland': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'Wales': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'Northern Ireland': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'United States': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Uruguay': { currency: 'UYU', symbol: '$U', rate: 39.0 },
  'Uzbekistan': { currency: 'UZS', symbol: 'so\'m', rate: 12250.0 },
  'Vanuatu': { currency: 'VUV', symbol: 'Vt', rate: 120.0 },
  'Vatican City': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Venezuela': { currency: 'VES', symbol: 'Bs.S', rate: 36.0 },
  'Vietnam': { currency: 'VND', symbol: '₫', rate: 24500.0 },
  'Yemen': { currency: 'YER', symbol: '﷼', rate: 250.0 },
  'Zambia': { currency: 'ZMW', symbol: 'ZK', rate: 26.5 },
  'Zimbabwe': { currency: 'ZWL', symbol: 'Z$', rate: 6500.0 },
  // Aliases and additional territories
  'USA': { currency: 'USD', symbol: '$', rate: 1.0 },
  'US': { currency: 'USD', symbol: '$', rate: 1.0 },
  'America': { currency: 'USD', symbol: '$', rate: 1.0 },
  'UK': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'United Kingdom': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'Great Britain': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'Britain': { currency: 'GBP', symbol: '£', rate: 0.79 },
  'UAE': { currency: 'AED', symbol: 'د.إ', rate: 3.67 },
  'Emirates': { currency: 'AED', symbol: 'د.إ', rate: 3.67 },
  'Dubai': { currency: 'AED', symbol: 'د.إ', rate: 3.67 },
  'Czech': { currency: 'CZK', symbol: 'Kč', rate: 22.5 },
  'Czechia': { currency: 'CZK', symbol: 'Kč', rate: 22.5 },
  'Korea': { currency: 'KRW', symbol: '₩', rate: 1320.0 },
  'Holland': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'The Netherlands': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'DR Congo': { currency: 'CDF', symbol: 'FC', rate: 2500.0 },
  'Democratic Republic of Congo': { currency: 'CDF', symbol: 'FC', rate: 2500.0 },
  'DRC': { currency: 'CDF', symbol: 'FC', rate: 2500.0 },
  'Republic of Congo': { currency: 'XAF', symbol: 'FCFA', rate: 605.0 },
  'Eswatini': { currency: 'SZL', symbol: 'L', rate: 18.5 },
  'Burma': { currency: 'MMK', symbol: 'K', rate: 2100.0 },
  'Timor-Leste': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Russian Federation': { currency: 'RUB', symbol: '₽', rate: 92.0 },
  'Macau': { currency: 'MOP', symbol: 'MOP$', rate: 8.05 },
  'Macao': { currency: 'MOP', symbol: 'MOP$', rate: 8.05 },
  'Hong Kong': { currency: 'HKD', symbol: 'HK$', rate: 7.82 },
  'Bosnia': { currency: 'BAM', symbol: 'KM', rate: 1.80 },
  'St. Lucia': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'St Lucia': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'St. Vincent': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'St Vincent': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'St. Kitts': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'St Kitts': { currency: 'XCD', symbol: 'EC$', rate: 2.70 },
  'Trinidad': { currency: 'TTD', symbol: 'TT$', rate: 6.78 },
  'New Caledonia': { currency: 'XPF', symbol: '₣', rate: 110.0 },
  'French Polynesia': { currency: 'XPF', symbol: '₣', rate: 110.0 },
  'Tahiti': { currency: 'XPF', symbol: '₣', rate: 110.0 },
  'Puerto Rico': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Guam': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Virgin Islands': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Bermuda': { currency: 'BMD', symbol: 'BD$', rate: 1.0 },
  'Cayman Islands': { currency: 'KYD', symbol: 'CI$', rate: 0.82 },
  'The Bahamas': { currency: 'BSD', symbol: 'B$', rate: 1.0 },
  'Turks and Caicos': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Aruba': { currency: 'AWG', symbol: 'ƒ', rate: 1.79 },
  'Curacao': { currency: 'ANG', symbol: 'ƒ', rate: 1.79 },
  'Bonaire': { currency: 'USD', symbol: '$', rate: 1.0 },
  'Martinique': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Guadeloupe': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Reunion': { currency: 'EUR', symbol: '€', rate: 0.92 },
  'Zanzibar': { currency: 'TZS', symbol: 'TSh', rate: 2510.0 },
  'North Macedonia': { currency: 'MKD', symbol: 'ден', rate: 56.5 },
};

/**
 * Updates currency rates in currencyData with live rates
 * Called by currencyService after fetching new rates
 * @param {Object} liveRates - Object mapping currency codes to rates
 */
export const updateCurrencyRates = (liveRates) => {
  if (!liveRates || typeof liveRates !== 'object') {
    return;
  }

  // Update rates for all countries
  Object.keys(currencyData).forEach(countryName => {
    const countryInfo = currencyData[countryName];
    const liveRate = liveRates[countryInfo.currency];

    if (liveRate && typeof liveRate === 'number') {
      currencyData[countryName].rate = liveRate;
    }
  });

  console.log('Currency rates updated in currencyData');
};

// Helper function to get currency info for a country
export const getCurrencyInfo = (countryName) => {
  return currencyData[countryName] || { currency: 'USD', symbol: '$', rate: 1.0 };
};
